common/models/Member.php
<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "member".
 *
 * @property integer $id
 * @property string $name
 * @property string $city
 * @property string $country
 * @property string $income
 */
class Member extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'member';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name', 'city', 'country', 'income'], 'required'],
            [['city'], 'string'],
            [['income'], 'number'],
            [['name', 'country'], 'string', 'max' => 255],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Name',
            'city' => 'City',
            'country' => 'Country',
            'income' => 'Income',
        ];
    }

    public function getUser()
    {
        return $this->hasOne(User::className(), ['id_member' => 'id']);
    }
}

frontend/controllers/MemberController.php
<?php

namespace frontend\controllers;

use Yii;
use yii\filters\AccessControl;
use common\models\Kredit;

class MemberController extends \yii\web\Controller
{
	public function behaviors()
    {
        return [

            'access' => [
                'class' => AccessControl::className(),
                'only' => ['index', 'kredit'],
                'rules' => [
                    [
                        'actions' => ['index', 'kredit'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }

    public function actionIndex()
    {
        return $this->render('index');
    }

    public function actionKredit()
    {
    	$model = new Kredit();

    	if ($model->load(Yii::$app->request->post()) && $model->validate()) {
    		
    		$model->id_owner = Yii::$app->user->identity->id_member;
    		$model->id_status = 1;

    		// Count harga cicilan per bulan

    		$cicilan = $model->kendaraan->harga / $model->jangka_cicilan;

    		$model->harga = $cicilan;

    		if ($model->save()) {

    			Yii::$app->getSession()->setFlash('success', 'Silahkan Menunggu KOnfirmasi');

    			return $this->redirect(['index']);
    			
    		} else {
    			return $this->render('kredit', [
	    			'model' => $model
	    		]);
    		}

    	} else {
    		return $this->render('kredit', [
    			'model' => $model
    		]);
    	}
    }

}

frontend/views/member/index.php
<?php
/* @var $this yii\web\View */
use yii\helpers\Html;

?>
<h1>Selamat datang</h1>

<br><br>

<?= Html::a('AJUKAN KREDIT', ['member/kredit'], ['class' => 'btn btn-primary btn-lg']); ?>

frontend/views/member/kredit.php
<?php

use yii\helpers\Html;
use yii\helpers\ArrayHelper;
use yii\widgets\ActiveForm;
use common\models\Kendaraan;

/* @var $this yii\web\View */
/* @var $model common\models\Kredit */
/* @var $form ActiveForm */
?>
<div class="member-kredit">
	<div class="container">
		<div class="row">
			<div class="col-xs-4 col-xs-offset-4">
				<?php $form = ActiveForm::begin(); ?>

			        <?=
			            $form->field($model, 'id_kendaraan') 
			             ->dropdownList(
			                 ArrayHelper::map(Kendaraan::find()->all(), 'id', 'nama'),
			                 ['prompt' => 'Pilih kendaraan']
			             )->label(
			                 'Kendaraan',
			                 ['class' => 'label-class']
			             )
			        ?>

			        <?=
			            $form->field($model, 'jangka_cicilan') 
			             ->dropdownList(
			                 $model->jangka_waktu,
			                 ['prompt' => 'Pilih jangka waktu cicilan']
			             )->label(
			                 'Lama Cicilan',
			                 ['class' => 'label-class']
			             )
			        ?>

			        <?=
				    	$form->field($model, 'agree')
				    		->checkbox([
				    			'checked' => false,
				    			'label' => 'Dengan ini saya menyetujui semua syarat dan ketentuan'
				    		]);
				    ?>
			    
			        <div class="form-group">
			            <?= Html::submitButton('Submit', ['class' => 'btn btn-primary']) ?>
			        </div>
			    <?php ActiveForm::end(); ?>
			</div>
		</div>
	</div>

</div><!-- member-kredit -->